on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest  # Runs on Windows

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Java (Required for Flutter & Android)
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'  # Stable JDK for Android
          java-version: '17'       # Java 17 (LTS)

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.4'  # Change if needed

      - name: Install Dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --debug

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build\app\outputs\flutter-apk\app-release.apk

  build-ios:
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.4'

      - name: Install Dependencies
        run: flutter pub get

      - name: Install CocoaPods (For iOS)
        run: |
          cd ios
          pod install
          cd ..

      - name: Build iOS IPA
        run: flutter build ipa --release

      - name: Upload IPA Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-ipa
          path: build/ios/ipa/*.ipa